version: '3.5'

services:
  python:
    build: .
    volumes:
      - .:/app

  db:
    image: mysql:8.0.16
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_USER: db_user
      MYSQL_DATABASE: db_name
      MYSQL_PASSWORD: db_password
    ports:
      - 33060:3306